### ISSUE TITLE
Add 'Table of Contents' in documentation

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/Moody-website#10]
Add 'Table of Contents' in `README.md`.

**Comment by Susmita-Dey** [comment]
@bhattabhi013 `README.md` file is short already. But I still what to know what things will be there under table of contents.

**Comment by bhattabhi013** [comment]
Something like this.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/47862474/193464430-7c0c7d7f-5cb0-4468-9531-c97e96cef188.png">

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Go ahead

**Comment by bhattabhi013** [comment]
Fixed by #36
