### ISSUE TITLE
There is unnecessary white space at the top of page 

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Moody-website#109]
### Description

 There is an unnecessary white space at the top of the page behind the navbar, can I work on this issue under Hacktoberfest 2022?

### Screenshots
Currently -
![image](https://user-images.githubusercontent.com/89779447/194722391-8bed1363-c534-4df4-9167-e0a31465fa6a.png)

After - 
![image](https://user-images.githubusercontent.com/89779447/194722418-4053732e-6f8c-41a4-bbd5-df922c2153b0.png)

### Additional information

I can do this by tweaking some margin settings

**Comment by Susmita-Dey** [comment]
Go ahead
