### ISSUE TITLE
The changes I made are not reflected on the website due to merge of some other pr 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#111]
### Description

I fixed the email link in footer and also the footer icons link in pr #89 but the current deployed version does not have those changes

### Screenshots

https://user-images.githubusercontent.com/94471189/194741229-50402b1b-3bc1-4ba9-8406-b60671d98abf.mp4

**Comment by Susmita-Dey** [comment]
Fix it
