### ISSUE TITLE
Add emoji mood changer 

### ISSUE THREAD

**Issue by Shivam-Katare** [Susmita-Dey/Moody-website#115]
### Description

Hey @Susmita-Dey,  I am thinking to add "Emoji Mood Changer" in the about section. Instead of just a basic emoji image in the about section, we can add an **Emoji Mood Changer**. So, whenever the user hovers over that div then, the emoji will change every time.

## Like This

https://user-images.githubusercontent.com/91705825/194753580-a5bb78b5-448a-4012-9800-95b89682c151.mp4

### Additional information

Let me know if it looks good. Then I will start working on it.

**Comment by Susmita-Dey** [comment]
People have to wait for getting their mood. I don't want the users to go through it as when they're angry they might not have patience.

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Would it look good in the website?

I can't finalize now. Thinking from end user point of view, there still lies a confusion whether it will be okay or not.

**Comment by Shivam-Katare** [comment]
Yeah @Susmita-Dey,  I think you're right. Maybe it will not look good on the website. But, if you want to see how it will look then, I can show you by implementing it.

**Comment by Susmita-Dey** [comment]
@Shivam-Katare I don't want to waste your time and also not to reject your PR. Better to close it.

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare I don't want to waste your time and also not to reject your PR. Better to close it.

Okay. Then close this issue. It's better to be close.
