### ISSUE TITLE
Improve Testemonials Section

### ISSUE THREAD

**Issue by stringer1000** [Susmita-Dey/Moody-website#119]
### Description

* Add hover effects
* Improve Contrast with background
* Disable user select in the section

### Screenshots

![image](https://user-images.githubusercontent.com/115400732/194854602-4c03b3ca-8a6b-4210-8722-b40f56ebcdad.png)
![image](https://user-images.githubusercontent.com/115400732/194854766-5422c48b-51e2-434a-9f3f-0a2b95fdb374.png)

**Comment by Susmita-Dey** [comment]
Seems like Duplicate issue. Check if this kind of thing already exists or not as an issue or PR

**Comment by imaaquibali** [comment]
@Susmita-Dey I'm closing this issue!
