### ISSUE TITLE
The Website don't have any Favicon

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Moody-website#12]
There is no favicon on the website, so can I use the logo of moody-website and make a favicon and put it on the website? Can I work on this under Hacktoberfest 2022

**Comment by minhaj-313** [comment]
I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best.

**Comment by adnansam110** [comment]
Can you assign this to me please @MohitNamdev22 ?

**Comment by MohitNamdev22** [comment]
> I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best.

Hey 👋, you can contribute to the project by finding issues on the project and creating the issue. Sorry guys but I'm also a contributor, and I want to work on this. You may find some different issue 👍

**Comment by minhaj-313** [comment]
Its Ok

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Go ahead
