### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Rohitchaudhary13** [Susmita-Dey/Moody-website#122]
### Description

The website is completely responsive but the UI breaks due to the go-to top icon, I want to solve this issue
Assign this to me!

### Screenshots

![Screenshot 2022-10-11 032811](https://user-images.githubusercontent.com/71605903/194958765-3e948172-7a3e-4ce5-bf08-f9cb334e8740.png)

**Comment by imaaquibali** [comment]
@Rohitchaudhary13 Go for it!
