### ISSUE TITLE
submit button  

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#17]
Hyperlinking the submit button.

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Share a screenshot

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Share a screenshot. Which button are you talking about?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Share a screenshot. Which button are you talking about?

https://user-images.githubusercontent.com/94471189/193451494-b2aae8ac-2438-4138-b121-39ea7be41817.mp4

**Comment by Susmita-Dey** [comment]
@Vanshiii203 We need backend for this to store data. But where you're thinking to link it?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 We need backend for this to store data. But where you're thinking to link it?

I was thinking to link it to the e-mail  so that the entered data will be send to the email to which we will link it.

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Let me create a form for that to take those data to email.

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Let me create a form for that to take those data to email.

okay!
