### ISSUE TITLE
Adding background illustrations and Glass effect on Contact section of Homepage

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Moody-website#2]
The current design of the contact page seems very simple. So can I work on the UI of the Homepage under Hacktoberfest 2022?

Before - 
![image](https://user-images.githubusercontent.com/89779447/193394731-61443e69-915f-4347-b276-9985d825f3f3.png)

After- 
![image](https://user-images.githubusercontent.com/89779447/193394716-3ccf8b16-5e7c-46fb-b53b-836d99224e10.png)

**Comment by Susmita-Dey** [comment]
Looks nice. Go ahead

**Comment by MohitNamdev22** [comment]
Great! 👍
