### ISSUE TITLE
Change mail id and it's link

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Moody-website#20]
Update the following email id to `moodyextension@gmail.com` in the Contact Us section.

![image](https://user-images.githubusercontent.com/79099734/193454698-ef42317d-ab36-4e3b-968c-474c0d2825ed.png)

**Comment by ramdhanihendrie** [comment]
I am interested in this issue. please assign it to me

**Comment by Susmita-Dey** [comment]
@ramdhanihendrie Go ahead
