### ISSUE TITLE
Feature: clean console 

### ISSUE THREAD

**Issue by Niravprajapati1** [Susmita-Dey/Moody-website#24]
Inspect this website in small screen size . you may notice that on clicking menu icon it log unnecessary text in console.

**Comment by Susmita-Dey** [comment]
@Niravprajapati1 How will you clean the console?

Also, attach an ss.

**Comment by Niravprajapati1** [comment]
Sure

**Comment by Niravprajapati1** [comment]
![IMG_20221002_190402](https://user-images.githubusercontent.com/83688779/193456838-a6580f2b-f073-4100-b1d2-cbad7d22cfad.jpg)
You can remove console.log() so console will be clean.

**Comment by Susmita-Dey** [comment]
@Niravprajapati1 I guess console is good for developers. Users won't check into it though.

**Comment by Niravprajapati1** [comment]
okay you can close this issue
