### ISSUE TITLE
Will improve the responsiveness of the webpage.

### ISSUE THREAD

**Issue by Anubhavgupta14** [Susmita-Dey/Moody-website#26]
Will improve the responsiveness of the webpage.
#Bug.
![res](https://user-images.githubusercontent.com/97956667/193457259-fbc2d559-ea6e-4d87-8472-4d109894b323.jpg)

**Comment by Anubhavgupta14** [comment]
Text is overlapping in the buttons, and Navbar should be fixed.

**Comment by Anubhavgupta14** [comment]
@Susmita-Dey Kindly Assigned it to me.

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 Check the website now once again.

**Comment by Anubhavgupta14** [comment]
It is still not looking good in mobile version.

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 Fix it then
