### ISSUE TITLE
Adding a pointer to the icons 

### ISSUE THREAD

**Issue by Mohasin-Haque** [Susmita-Dey/Moody-website#27]
I want to add the pointer to the icons as it doesn't look nice without it in the footer section
![image](https://user-images.githubusercontent.com/72180173/193457320-06324a99-a7e9-4466-ab56-5deacfcd9267.png)

**Comment by Vanshiii203** [comment]
> I want to add the pointer to the icons as it doesn't look nice without it in the footer section ![image](https://user-images.githubusercontent.com/72180173/193457320-06324a99-a7e9-4466-ab56-5deacfcd9267.png)
I am already working on this #4
