### ISSUE TITLE
[FEATURE] Add glass effect

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/Moody-website#37]
### Description

Add a glass effect on the main content.

### Screenshots

<img width="696" alt="image" src="https://user-images.githubusercontent.com/47862474/193469298-39ca6051-00bf-4345-8faa-aee66a987c68.png">

**Comment by AbhishekJadhav2002** [comment]
!assign

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Show me a screen record in the PR you'll be creating.
