### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#4]
adding hover effect and transition to the icons, adding the links to them and adding cursor pointer 
![Screenshot (425)](https://user-images.githubusercontent.com/94471189/193395658-1ef7f979-a0df-46ae-bf11-9f7cebe8b771.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 I have create accounts for moody first.

**Comment by Vanshiii203** [comment]
> @Vanshiii203 I have to create accounts for moody first.

Okay

**Comment by omthakare16** [comment]
Hey , Can you assign me , Can I work on this issue ?

**Comment by Susmita-Dey** [comment]
@omthakare16 Since @Vanshiii203 made the issue, it would be assigned to her first. If she fails, then I'll assign it to you.

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Note the following things to update the links:-
- Mail id:- moodyextension@gmail.com
- Twitter:- https://twitter.com/ExtensionMoody
- GitHub(Extension):- https://github.com/Susmita-Dey/Moody
- GitHub(Website):- https://github.com/Susmita-Dey/Moody-website

Remove Facebook and add GitHub logo instead.

**Comment by Niravprajapati1** [comment]
Add assigned label

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Note the following things to update the links:-
> 
> * Mail id:- [moodyextension@gmail.com](mailto:moodyextension@gmail.com)
> * Twitter:- https://twitter.com/ExtensionMoody
> * GitHub(Extension):- https://github.com/Susmita-Dey/Moody
> * GitHub(Website):- https://github.com/Susmita-Dey/Moody-website
> 
> Remove Facebook and add GitHub logo instead.

Okayy
