### ISSUE TITLE
[FEATURE]adding glass effect to the navbar on scrolling 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#41]
### Description

Before-
![Screenshot (441)](https://user-images.githubusercontent.com/94471189/193506038-6ac8a133-963b-48cd-80ce-a372f9065fb1.png)

### Screenshots

after-
https://user-images.githubusercontent.com/94471189/193506016-36b43d62-7199-4e72-82f3-7ac0c4b22865.mp4

**Comment by Susmita-Dey** [comment]
Looks good by itself. Not needed now.
