### ISSUE TITLE
Please assign me the Update Readme.md #45

### ISSUE THREAD

**Issue by guptamanu409** [Susmita-Dey/Moody-website#48]
### What would you like to share?

I would like to make it more informative for all those who want to contribute to your project.

**Comment by Susmita-Dey** [comment]
@guptamanu409 There's a `CONTRIBUTING.md` file for that. But still I wanna know what changes you're thinking to add.

**Comment by guptamanu409** [comment]
You told me to raise the issue now you are asking what am i going to do.... Please i'm new into this.... Teach me if i'm wrong somewhere but please don't do this
![image](https://user-images.githubusercontent.com/55289731/193566014-b0a9332f-29f6-4550-abad-e44745f84746.png)

**Comment by Susmita-Dey** [comment]
@guptamanu409 Sorry my bad but I'm assigning it to you. But made the chanegs I asked to do in your PR.

**Comment by guptamanu409** [comment]
Mam it's done Kindly review it once mam

**Comment by guptamanu409** [comment]
I got to learn about first raising the issue then only correct it. Thanks for guiding me.
![ThankYouThanksGIF](https://user-images.githubusercontent.com/55289731/193569336-4620812e-1472-40af-8503-8ee8917de129.gif)
