### ISSUE TITLE
Some improvement in website 

### ISSUE THREAD

**Issue by YasirObaibullah99** [Susmita-Dey/Moody-website#5]
The footer section on the website is not looking good So I would like to make it better

**Comment by Susmita-Dey** [comment]
@YasirObaibullah99 Show me before making PR

**Comment by YasirObaibullah99** [comment]
Hey I have added a footer on the website check this video 
[Screencast from 02-10-22 08:47:16 PM IST.webm](https://user-images.githubusercontent.com/83706868/193461790-5cf158b6-4909-4a37-af7a-8a24425a7beb.webm)

**Comment by Susmita-Dey** [comment]
@YasirObaibullah99 Check issue #4

**Comment by YasirObaibullah99** [comment]
basically, I need to add a GitHub icon and remove the Facebook icon If I am not wrong

**Comment by Susmita-Dey** [comment]
@YasirObaibullah99 She is also working on that.

**Comment by YasirObaibullah99** [comment]
But I have made Footer and she is linking the link to a button so First Can I make PR and after that, she can link with those links which have been given in issue #4
