### ISSUE TITLE
Making navbar responsive

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#6]
Making navbar responsive. The alignment of the list and the button in navbar can be changed
Also I think the logo is enough the name need not to be written in the navbar 
![Screenshot (426)](https://user-images.githubusercontent.com/94471189/193395749-a7f39606-f7cb-41dc-a3e0-04f77feb924c.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Go ahead
