### ISSUE TITLE
[Change] <I want to change the logo and social icons hover effetc>

### ISSUE THREAD

**Issue by imaaquibali** [Susmita-Dey/Moody-website#61]
### Description

Hi @Susmita-Dey I want to the change the logo of the site. It's not look good. I want to create an logo which matches the theme of the site and looks attractive with the theme and changes the footer social icons effects which matches the theme of the site.

I want to work on this issue under the Hactoberfest2022. Please assign me this issue so i work on this issue.  I'm happy to work on this issue

`thank you`

**Comment by Saurabhk1975** [comment]
i want to work on this assign me @Susmita-Dey
