### ISSUE TITLE
[FEATURE] Improve navigation bar design

### ISSUE THREAD

**Issue by rtewari056** [Susmita-Dey/Moody-website#64]
### Description

The overall look of the navigation bar is not that great for a good user experience and can be improved by adding additional styling.

### Screenshots

Right now the navigation bar looks like this

![screenshot-github](https://user-images.githubusercontent.com/75976169/193749295-51e7c84d-686b-471d-aed5-2bba4bae3efb.png)

### Additional information

I want to work on this issue under Hacktoberfest 2022

**Comment by rtewari056** [comment]
@Susmita-Dey Kindly assign me this issue

**Comment by imaaquibali** [comment]
@rtewari056 go ahead!

**Comment by hansupadhyay007** [comment]
I want to work on this issue please assign me..

**Comment by hansupadhyay007** [comment]
Now your Navbar is looking like this, kindly accept my PR.
![navbar](https://user-images.githubusercontent.com/112337432/194129990-eada3a6e-be77-45b2-ad22-3940e4f788fc.jpg)

**Comment by hansupadhyay007** [comment]
@Susmita-Dey I want to work on this issue. Kindly assign me this task.

**Comment by mindexpert7546** [comment]
can you assign me

**Comment by Susmita-Dey** [comment]
@mindexpert7546 @hansupadhyay007 You guys can check other issues as this has already been assigned to @rtewari056
