### ISSUE TITLE
Contact us Form required validation missing

### ISSUE THREAD

**Issue by sethisagar** [Susmita-Dey/Moody-website#68]
### Description

On contact us form if you submit blank it showing error in a weird way. Warning message should be proper. 

### Screenshots

![Uploading Screenshot_2022-10-04-15-52-02-030_com.android.chrome.jpg…]()

**Comment by sethisagar** [comment]
![Uploading Screenshot_2022-10-04-15-52-02-030_com.android.chrome.jpg…]()

**Comment by sethisagar** [comment]
Should I work on this?

**Comment by AbhishekJadhav2002** [comment]
Currently working on the same #52

**Comment by imaaquibali** [comment]
@sethisagar sorry someone is already working on that issue. please create another issue
