### ISSUE TITLE
Navigation bar is not auto hiding when click on home

### ISSUE THREAD

**Issue by sethisagar** [Susmita-Dey/Moody-website#70]
### Description

Navigation bar is not auto hiding when click on home. 
On mobile.

**Comment by imaaquibali** [comment]
@sethisagar can you describe more. If possible plz attached ss also

**Comment by sethisagar** [comment]
@imaaquibali Added the video [here ](https://drive.google.com/file/d/11yzMWvCJ45d5Sht9LIje7Xif5t0nforT/view?usp=drivesdk)to describe the issue.
Created the PR with [Fix](https://github.com/Susmita-Dey/Moody-website/pull/96).
