### ISSUE TITLE
Improve the responsiveness for extra small devices.

### ISSUE THREAD

**Issue by surbhi400** [Susmita-Dey/Moody-website#75]
### Description

The website is not completely responsive for extra small devices.  The buy me a coffee button is overlapping its text and slight changes is required in the navbar and footer too for extra small devices.

### Screenshots

![moody-website-update](https://user-images.githubusercontent.com/77582783/193976962-0790afad-9e33-405f-906d-c0c3f10d01dc.png)

**Comment by prakhartiwari0** [comment]
Can I work on this issue?

**Comment by prakhartiwari0** [comment]
**Just a suggestion**: We can also position these buttons vertically instead of horizontally to improve the look.
![image](https://user-images.githubusercontent.com/65062036/193982303-cd537ebe-e6a6-42c0-a989-208160342bf5.png)

**Comment by surbhi400** [comment]
@Susmita-Dey I created this issue so can you please assign me this issue.

**Comment by prakhartiwari0** [comment]
I may assist you @surbhi400

**Comment by imaaquibali** [comment]
@surbhi400 go for it!
