### ISSUE TITLE
Background color of NavBar and the size of logo of Moody is up to the mark

### ISSUE THREAD

**Issue by arpitghura** [Susmita-Dey/Moody-website#80]
### Description

The background color of NavBar is not up to the mark. 
The logo size is also large. 
We should create a small-sized attractive logo or we can resize the existing one. 

Update the NavBar background color and logo so that the website looks cool. 

### Screenshots

![image](https://user-images.githubusercontent.com/41796013/194108538-1a9e7865-0f1f-4109-b98e-365815947bff.png)

**Comment by imaaquibali** [comment]
@arpitghura Someone is already working on that issue!
