### ISSUE TITLE
The email is not hyperlinked correctly in footer 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#85]
### Description

hyperlinking the email link correctly in footer and making the socials open in new  tab 

### Screenshots

https://user-images.githubusercontent.com/94471189/194221558-f20841f0-8421-4414-9b91-d08580f2d476.mp4

**Comment by rosdyana** [comment]
Easy fix.

https://github.com/Susmita-Dey/Moody-website/blob/bba5f49d3b6a31a6fab088ca89ccfd20d9b0c124/index.html#L308

Should be

`     <a href="mailto:moodyextension@gmail.com"><b>Moody</b></a>.`
