### ISSUE TITLE
Buttons don't look good on small screen device

### ISSUE THREAD

**Issue by swapn652** [Susmita-Dey/Moody-website#9]
![image](https://user-images.githubusercontent.com/70851202/193420611-e6bd9580-459a-4b33-8543-43ccf143ba5d.png)

**Comment by Mahich123** [comment]
I would like to fix this issue . 
Can I work in this ?

**Comment by Susmita-Dey** [comment]
@swapn652 @Mahich123 Leave this issue for a while as someone is working in this section.

**Comment by AkashSharma001** [comment]
Could you please assign me? I would like to fix this issue. @Susmita-Dey

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thankyou.
