### ISSUE TITLE
About header is missing in the navbar 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Moody-website#90]
### Description

About header is missing in the navbar 

### Screenshots

![Screenshot (468)](https://user-images.githubusercontent.com/94471189/194269115-c2986b4b-40cf-4011-adfd-25a456ada463.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Remove Services and shift Testimonials in that place and then add About in place of Testimonials.

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Remove Services and shift Testimonials in that place and then add About in place of Testimonials.

Okay!
