### ISSUE TITLE
The footer section is not properly aligned

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Moody-website#97]
### Description

The footer of the website is shifted toward the left, can I work on the issue under hacktoberfest 2022?

### Screenshots

![image](https://user-images.githubusercontent.com/89779447/194584544-3cb0b7e8-64b5-4502-b508-10ebb6b5cc6a.png)

### Additional information

It can be solved by margin properties

**Comment by sumitkr2000** [comment]
@MohitNamdev22 I have already solve this issue and created a pr

**Comment by MohitNamdev22** [comment]
Oops my bad
