### ISSUE TITLE
[FEATURE] <update navbar section>

### ISSUE THREAD

**Issue by imaaquibali** [Susmita-Dey/Moody-website#99]
### Description

Added ABOUT link in navbar and link it to the about section.

**Comment by Susmita-Dey** [comment]
@imaaquibali This was assigned to @Vanshiii203. Why are you doing this? 

I've added you as maintainer to assign and review PRs. Not to do this kind of bullshits. You're creating issues and getting yourself assigned and then making PRs for that and also merging it.

**Comment by imaaquibali** [comment]
@Susmita-Dey I didn't check the issue before creating. My bad.

**Comment by imaaquibali** [comment]
@Susmita-Dey  I removed the hacktoberfest tag.

**Comment by Susmita-Dey** [comment]
@imaaquibali If you want to contribute, create issues and ping me. When you make PRs, request review from me for your contribution. Don't do like this all alone.

**Comment by imaaquibali** [comment]
@Susmita-Dey sure sir XD
